'use strict';
const $=id=>document.getElementById(id),layers=[
 {name:'Reality',subtitle:'THE AIRCRAFT',rate:1,caption:'A SAFE PLACE TO WAKE.',gravity:'Stable / 1.0 G',title:'Keep the exit in sight.',copy:'This is your reference clock. Complete the dream objectives below, then ride the synchronized kicks back here.',team:[['YUSUF',380,265,'The dream connection is monitored from reality. This simulator simplifies the team’s roles.']]},
 {name:'The city',subtitle:'RAIN & PURSUIT',rate:20,caption:'THE CITY IS A CONSTRUCT.',gravity:'Stable / 1.0 G',title:'Secure the route.',copy:'Clear a route for the van. The city supports every layer beneath it; a disruption here changes the hotel’s gravity.',task:'Secure the van route',team:[['YUSUF',420,290,'Driver · Holds the first dream layer and prepares the van’s kick.'],['COBB',280,235,'Extractor · Keeps the team focused on the shared objective.']]},
 {name:'The hotel',subtitle:'SHIFTING GRAVITY',rate:400,caption:'GRAVITY IS BORROWED FROM ABOVE.',gravity:'Stable / 1.0 G',title:'Prepare the escape.',copy:'Establish an elevator escape for the team. If gravity shifts, stabilize the layer before preparing its kick.',task:'Prepare the elevator',team:[['ARTHUR',395,258,'Point man · Coordinates the hotel’s escape and the second kick.'],['ARIADNE',240,315,'Architect · Understands how the constructed space fits together.']]},
 {name:'The fortress',subtitle:'SNOW & SECRETS',rate:8000,caption:'AN IDEA WAITS BEHIND THE VAULT.',gravity:'Stable / 1.0 G',title:'Plant the idea.',copy:'Once the city route and hotel escape are ready, choose an idea the subject could experience as their own.',team:[['EAMES',330,260,'Forger · Helps the subject reach the emotional centre of the mission.'],['FISCHER',470,225,'Subject · The idea must feel like a personal realization, not an order.']]},
 {name:'Limbo',subtitle:'UNBUILT DREAM SPACE',rate:160000,caption:'TIME HAS LOST ITS ANCHOR.',gravity:'Uncertain',title:'Do not lose yourself.',copy:'Limbo is the mission’s failure state. You can inspect it freely, but a collapsed layer or an expired wake-up window strands the mission here.',team:[['COBB',360,310,'A reminder · Without an anchor, a dream can begin to feel like reality.']]}
];
let state,lastTick=0,logs=[];function initial(){return{phase:'idle',selected:1,remaining:180,elapsed:0,stable:[100,88,85,80,0],tasks:[false,false,false,false],armed:[false,false,false,false],charges:3,gravity:false,rotated:false,threatAt:18}}
state=initial();
function fmt(n){n=Math.max(0,Math.floor(n));return String(Math.floor(n/3600)).padStart(2,'0')+':'+String(Math.floor(n%3600/60)).padStart(2,'0')+':'+String(n%60).padStart(2,'0')}
function log(message,type=''){logs.unshift({time:fmt(state.elapsed),message,type});logs=logs.slice(0,50);$('mission-log').innerHTML=logs.map(v=>`<div class="entry ${v.type}"><time>${v.time}</time><span>${v.message}</span></div>`).join('')}
const svgNS='http://www.w3.org/2000/svg';
function building(x,y,w,d,h,color='#5d8c96'){return `<g fill="none" stroke="${color}" stroke-width=".8"><path d="M${x} ${y}l${w} ${w*.47} ${d} ${-d*.47} ${-w} ${-w*.47}Z" fill="#1a303b"/><path d="M${x} ${y}v${-h}l${w} ${w*.47}v${h}m0 ${-h}l${d} ${-d*.47}v${h}m${-d} ${-h+d*.47}l${-w} ${-w*.47} ${d} ${-d*.47} ${w} ${w*.47}"/><path d="M${x+5} ${y-h+16}l${w-10} ${(w-10)*.47}m${-w+10} 12l${w-10} ${(w-10)*.47}m${-w+10} 12l${w-10} ${(w-10)*.47}" opacity=".35"/></g>`}
function draw(){const sel=state.selected;let s='<g stroke="#355967" fill="none" stroke-width=".6"><path d="M95 300L380 160 665 300 380 445Z"/><path d="M140 322l285-140m-230 167 285-140m-230 167 285-140M335 183l285 140m-340-112 285 140m-340-112 285 140"/></g>';
 if(sel===1){for(let r=0;r<4;r++)for(let c=0;c<4;c++){const x=155+c*75+r*45,y=235+c*35-r*23,h=42+((r*17+c*23)%85);if((r===2&&c===2)||(r===1&&c===2))continue;s+=building(x,y,44,39,h)}s+='<path d="M155 314l275-133m-210 159 280-135" stroke="#8fc9c7" stroke-dasharray="5 5" opacity=".6"/><g stroke="#9aabb1" opacity=".17">'+Array.from({length:35},(_,i)=>`<path d="M${100+i*17} ${60+i%5*19}l-14 46"/>`).join('')+'</g>';}
 if(sel===2){s+='<g stroke="#759ba7" fill="none"><path d="M130 330L350 200 645 320 430 450Z"/><path d="M130 330V150L350 20 645 140V320M130 150L430 270 645 140M430 270V450M350 20V200"/><path d="M235 267V161L350 96 537 174V280M235 161L420 240 537 174M420 240V347"/><path d="M130 195L430 315 645 185M130 240L430 360 645 230M130 285L430 405 645 275" opacity=".3"/><path d="M340 298V199l47-26 43 19v103M340 199l45 19 45-26M385 218v102" stroke="#a0d7cb"/><path d="M341 282l44 19 43-25" stroke="#a0d7cb" stroke-dasharray="3 5"/></g>';}
 if(sel===3){s+='<g fill="#1c303b" stroke="#4a737f"><path d="M75 320L205 118 275 227 345 90 445 210 570 74 696 326Z"/><path d="M166 179l39-61 35 55-22-5-14 11-17-7Zm138-29 41-60 39 51-24-4-20 20-18-12Zm235-33 31-43 29 59-29-9-16 9Z" fill="#7d9fa6"/></g>';s+=building(285,319,130,100,95)+building(245,300,40,40,120)+building(415,355,40,40,120);s+='<path d="M371 352V298l28-14 22 10v36" stroke="#b4ddd3" fill="none"/><g fill="#bbd3d0" opacity=".4">'+Array.from({length:50},(_,i)=>`<circle cx="${70+i*13%620}" cy="${35+i*31%350}" r="1"/>`).join('')+'</g>';}
 if(sel===4){for(let i=0;i<20;i++)s+=building(110+i*27,250+(i%4)*25,24,27,60+i%6*20,i%2?'#766c83':'#4c6876');s+='<path d="M0 360Q140 310 240 370T480 370T760 370M0 385Q140 335 240 395T480 395T760 395" fill="none" stroke="#547f8a"/>';}
 if(sel===0){s='<g stroke="#7799a1" fill="none" stroke-width="1"><path d="M90 280Q130 223 195 228L310 249 390 190 422 194 390 270 582 302Q637 322 655 346L408 315 342 364 309 357 337 304 171 286 128 305 93 300 119 274Z"/><path d="M195 228Q215 246 206 285M227 237l-9 50M247 241l-9 50M267 244l-9 50M287 247l-9 50M426 275l-9 41M446 278l-9 41M466 282l-9 41M486 286l-9 41M506 289l-9 41M526 293l-9 41M546 296l-9 41" opacity=".4"/><circle cx="379" cy="268" r="105" opacity=".12"/><circle cx="379" cy="268" r="160" opacity=".08"/></g>';}
 $('architecture').innerHTML=s;transform();$('markers').innerHTML='';layers[sel].team.forEach(([name,x,y,description])=>{const g=document.createElementNS(svgNS,'g');g.setAttribute('class','team-marker');g.setAttribute('transform',`translate(${x} ${y})`);g.setAttribute('role','button');g.setAttribute('tabindex','0');g.setAttribute('aria-label','Inspect '+name);g.innerHTML='<circle r="15"/><circle class="dot" r="3"/><text x="20" y="3">'+name+'</text>';g.onclick=()=>show('<div class="eyebrow">TEAM TELEMETRY / '+layers[sel].name.toUpperCase()+'</div><h2>'+name+'</h2><p>'+description+'</p><p>Connection: '+(state.phase==='running'?'active':'standby')+' · Layer stability: '+state.stable[sel]+'%</p>');g.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();g.onclick()}};$('markers').append(g)});}
function transform(){const rotation=(state.rotated?12:0)+(state.selected===2&&state.gravity?28:0);$('architecture').style.transform=`rotate(${rotation}deg)`;$('rotate').setAttribute('aria-pressed',state.rotated)}
function select(i){state.selected=i;render();draw();}
function render(){const l=layers[state.selected],s=state.selected,running=state.phase==='running',playing=running||state.phase==='paused',done=state.phase==='won'||state.phase==='lost';
 document.querySelectorAll('.layer').forEach(b=>{const i=Number(b.dataset.layer);b.classList.toggle('active',i===s);b.classList.toggle('ready',!!state.tasks[i]);b.setAttribute('aria-pressed',i===s)});
 $('rate').textContent=l.rate.toLocaleString()+'×';$('view-label').textContent=(s===4?'LIMBO':s===0?'REALITY':'LAYER 0'+s)+' / '+l.name.toUpperCase();$('dream-caption').textContent=l.caption;
 $('objective-title').textContent=l.title;$('objective-copy').textContent=l.copy;$('objective-tag').textContent=s===0?'THE ANCHOR':s===4?'BEYOND THE MISSION':'LAYER OBJECTIVE';$('gravity').textContent=s===2&&state.gravity?'Disrupted / 0.0 G':l.gravity;$('projections').textContent=s===4?'Unbounded':s===0?'—':state.stable[s]<60?'Hostile':'Dormant';
 $('phase').textContent={idle:'STANDBY',running:'CONNECTED',paused:'PAUSED',won:'AWAKE',lost:'STRANDED'}[state.phase];$('countdown').innerHTML=String(Math.floor(Math.ceil(state.remaining)/60)).padStart(2,'0')+'<span>:</span>'+String(Math.ceil(state.remaining)%60).padStart(2,'0');$('timer-bar').style.width=state.remaining/180*100+'%';$('local-clock').textContent=fmt(state.elapsed*l.rate);
 $('stability-value').textContent=s===4?'UNKNOWN':state.stable[s]+'%';$('stability-bar').style.width=state.stable[s]+'%';$('stability-bar').style.background=state.stable[s]<40?'var(--red)':'var(--cyan)';$('stabilize').disabled=!running||s===0||s===4||state.charges===0||state.stable[s]===100;$('charge-count').textContent=state.charges+' charges';
 $('task-controls').innerHTML='';if(s>0&&s<4){if(state.tasks[s]){const p=document.createElement('p');p.textContent='✓ Objective complete';p.style.color='var(--cyan)';$('task-controls').append(p)}else if(s===3){['“I choose my own future.”','“Obey this instruction.”','“Forget who you are.”'].forEach((v,i)=>{const b=document.createElement('button');b.textContent=v;b.disabled=!running||!state.tasks[1]||!state.tasks[2];b.onclick=()=>plant(i);$('task-controls').append(b)})}else{const b=document.createElement('button');b.textContent=l.task;b.disabled=!running||(s===2&&!state.tasks[1])||(s===2&&state.gravity);b.onclick=()=>complete(s);$('task-controls').append(b)}}
 const armed=state.armed.filter(Boolean).length;$('armed-count').textContent=armed+' / 3';const canArm=running&&s>0&&s<4&&state.tasks[3]&&!state.armed[s]&&state.stable[s]>=35&&(s===3||state.armed[s+1])&&!(s===2&&state.gravity);$('arm').disabled=!canArm;$('arm').textContent=state.armed[s]?'✓ Kick armed':s===0||s===4?'Select a dream layer':!state.tasks[3]?'Plant the idea first':s<3&&!state.armed[s+1]?'Arm the deeper layer first':'Arm this layer’s kick';
 $('execute').disabled=!running||armed!==3||state.stable.slice(1,4).some(v=>v<35)||state.gravity;$('pause').disabled=!playing;$('pause').textContent=state.phase==='paused'?'Resume mission ▶':'Pause mission Ⅱ';$('start').disabled=playing;$('start').innerHTML=done?'Run another mission <span>↘</span>':'Begin the mission <span>↘</span>';$('session-note').textContent=running?'Prepare city → hotel → fortress. Then arm kicks 3 → 2 → 1.':state.phase==='paused'?'Mission paused. Resume when you are ready.':done?(state.phase==='won'?'Mission complete. The team is awake.':'The team is stranded. Reset to try again.'):'Explore the layers first, or start the 3-minute challenge.';
 $('disruption').disabled=done||state.phase==='paused'||state.gravity;$('clear-disruption').disabled=!state.gravity||state.phase==='paused'||done;$('log-state').textContent=playing?'CONNECTION ACTIVE':done?'SESSION COMPLETE':'AWAITING CONNECTION';document.body.classList.toggle('win',state.phase==='won');document.body.classList.toggle('fail',state.phase==='lost');
 for(let i=0;i<4;i++){const n=$('kick-'+i);n.classList.toggle('armed',state.armed[i]||false);n.classList.toggle('fired',state.phase==='won');n.querySelector('i').textContent=state.phase==='won'?'✓':state.armed[i]?'●':i===0?'◈':'○';}}
function complete(s){if(state.phase!=='running'||state.tasks[s]||(s===2&&(!state.tasks[1]||state.gravity)))return;state.tasks[s]=true;log(s===1?'City route secured. Descend to the hotel.':'Elevator escape prepared. Descend to the fortress.','success');render();}
function plant(i){if(state.phase!=='running'||!state.tasks[1]||!state.tasks[2]||state.tasks[3])return;if(i===0){state.tasks[3]=true;log('The subject accepts the idea as their own. Arm kicks: fortress → hotel → city.','success')}else{state.stable[3]=Math.max(0,state.stable[3]-20);log('The idea feels imposed. Projections resist. Fortress stability −20.','warning');if(!state.stable[3])return lose('The fortress collapsed. The team fell into limbo.')}render();}
function start(){state=initial();state.phase='running';logs=[];lastTick=Date.now();log('Dream connection established. Wake-up window: 3 minutes.');log('First objective: secure the city van route.');render();draw();}
function reset(){state=initial();logs=[];log('Interface reset. Inspect the dream layers, or begin a mission.');render();draw();}
function lose(reason){state.phase='lost';state.selected=4;log(reason,'warning');render();draw();show('<div class="eyebrow">CONNECTION LOST</div><h2>Stranded in limbo.</h2><p>'+reason+'</p><p>Complete the city and hotel objectives, plant the idea, then arm kicks from layer 3 to layer 1. Keep stability above 35% and restore gravity before synchronizing.</p><button class="primary" id="restart-modal">Try the mission again ↘</button>');}
function disrupt(){if(state.gravity||state.phase==='won'||state.phase==='lost'||state.phase==='paused')return;state.gravity=true;if(state.phase==='running'){state.stable[2]=Math.max(0,state.stable[2]-15);state.armed[2]=false;}log('City disruption propagates downward. Hotel gravity lost.','warning');if(!state.stable[2]&&state.phase==='running')return lose('The hotel collapsed after a gravity disruption.');render();transform();}
function tick(){if(state.phase!=='running')return;const now=Date.now(),dt=Math.min((now-lastTick)/1000,2);lastTick=now;state.elapsed+=dt;state.remaining=Math.max(0,180-state.elapsed);if(state.remaining<=0){state.remaining=0;return lose('The wake-up window closed before the team returned.')}if(state.elapsed>=state.threatAt){const layer=1+Math.floor(state.threatAt/18)%3;state.stable[layer]=Math.max(0,state.stable[layer]-12);if(state.stable[layer]<35)state.armed[layer]=false;log(layers[layer].name+': subconscious interference. Stability −12.','warning');state.threatAt+=18;if(!state.stable[layer])return lose(layers[layer].name+' collapsed. The team fell into limbo.');}render();}
function show(html){$('modal-content').innerHTML=html;if(!$('modal').open)$('modal').showModal()}
$('start').onclick=start;$('pause').onclick=()=>{if(state.phase==='running'){state.phase='paused';log('Mission paused. All dream clocks held.')}else if(state.phase==='paused'){state.phase='running';lastTick=Date.now();log('Mission resumed.')}render();};$('reset').onclick=()=>show('<div class="eyebrow">DISCONNECT</div><h2>Reset the mission?</h2><p>This clears the objectives, clocks and mission log.</p><button class="primary" id="reset-modal">Reset the interface ↺</button>');
$('modal').addEventListener('click',e=>{if(e.target.id==='restart-modal'){ $('modal').close();start();}if(e.target.id==='reset-modal'){$('modal').close();reset();}});
$('stabilize').onclick=()=>{const s=state.selected;if(state.phase!=='running'||s<1||s>3||!state.charges||state.stable[s]===100)return;state.charges--;state.stable[s]=Math.min(100,state.stable[s]+25);log(layers[s].name+' stabilized. +25 stability.','success');render();};
$('arm').onclick=()=>{if($('arm').disabled)return;state.armed[state.selected]=true;log(layers[state.selected].name+' kick armed.','success');render();};
$('execute').onclick=()=>{if($('execute').disabled)return;state.phase='won';state.selected=0;log('Synchronized kicks fired: fortress → hotel → city → reality.','success');log('The idea holds. All team members are awake.','success');render();draw();show('<div class="eyebrow">MISSION COMPLETE / REALITY</div><h2>You found the way back.</h2><p>The idea was planted and all three kicks were synchronized. The team returned with '+Math.ceil(state.remaining)+' seconds left in the wake-up window.</p><p>Next challenge: inject a gravity disruption during the mission and restore it before the final kick.</p><button class="primary" id="restart-modal">Run another mission ↘</button>');};
$('rotate').onclick=()=>{state.rotated=!state.rotated;transform()};$('disruption').onclick=disrupt;$('clear-disruption').onclick=()=>{if($('clear-disruption').disabled)return;state.gravity=false;log('Gravity restored. The hotel can prepare its escape.','success');render();transform()};
$('briefing').onclick=()=>show('<div class="eyebrow">OPERATION / ORIGIN</div><h2>Plant an idea.<br>Bring everyone home.</h2><p>You are the mission controller in an original, simplified fan scenario inspired by Christopher Nolan’s Inception.</p><ol><li>Begin the mission. In the city, secure the van route.</li><li>Select the hotel and prepare its elevator escape.</li><li>Select the fortress. Plant an idea that sounds like a personal choice.</li><li>Arm kicks in order: fortress (3), hotel (2), city (1).</li><li>Synchronize all kicks before reality’s three-minute window closes.</li></ol><p>Subconscious interference reduces stability every 18 reality seconds. You have three stabilization charges. All layers need at least 35% stability for the final kick. Restore any gravity disruption first.</p><p>The clocks use an illustrative 20× multiplier per nested layer. The countdown, team roles, objectives and failure rules are game abstractions, not precise measurements or a recreation of the film’s plot. The interface contains film spoilers.</p><p>Pause at any time. Switching tabs pauses an active mission. Your session stays in this tab; reset starts fresh. Team markers open details, and rotate changes the architecture view.</p><p><a href="https://www.legendary.com/film/inception/" target="_blank" rel="noopener">About the original film ↗</a></p>');
$('close-modal').onclick=()=>$('modal').close();document.querySelectorAll('.layer').forEach(b=>b.onclick=()=>select(Number(b.dataset.layer)));document.addEventListener('visibilitychange',()=>{if(document.hidden&&state.phase==='running'){state.phase='paused';log('Tab hidden. Mission automatically paused.');render();}});setInterval(tick,500);log('PASIV interface ready. Select a layer to inspect its architecture.');render();draw();
